name: .NET Core Build/Test

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore Application
    - name: Build
      run: dotnet build Application --configuration Release --no-restore
    - name: Test
      run: dotnet test Application --no-restore --verbosity normal
