name: .NET Core Tests

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore .\Application\Salvation.CoreTests\
    - name: Build
      run: dotnet build .\Application\Salvation.CoreTests\ --configuration Release --no-restore
    - name: Test 
      run: dotnet test .\Application\Salvation.CoreTests\ --no-restore --verbosity normal
